#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: Mod from P3TERX
# For NanoPi R2S slim
#=================================================

name: Build R2S OpenWrt slim

on:
#  release:
#    types: published
  push:
    branches:
      - master
    paths:
      - '.github/workflows/openwrt-r2s-slim.yml'
      - 'r2s.config'
  schedule:
    - cron: 30 20 * * *
  watch:
    types: started

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  CONFIG_FILE: r2s.config
  DIY_SH: r2s_diy.sh
  SSH_ACTIONS: false
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: false
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk
        sudo docker image prune -a -f
        sudo apt-get update
        sudo apt-get -y --no-install-recommends install build-essential asciidoc binutils bison bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf python3
        curl https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh  | sed '/#/d' | sed 's/\\//g' | sed 's/exit 0//g' | sed 's/sudo apt -y install//g' | sed 's/sudo apt-get -y install//g' | sed 's/:i386//g' | xargs sudo apt-get -y --no-install-recommends install
        git config --global user.name "actions"
        git config --global user.email "actions@github.com"
        
    - name: Install Friendlyarm repo
      run: |
        git clone https://github.com/friendlyarm/repo
        sudo cp repo/repo /usr/bin/
        

    - name: Download Source
      run: |
        rm -rf friendlywrt-rk3328
        mkdir friendlywrt-rk3328
        cd friendlywrt-rk3328
        repo init -u https://github.com/friendlyarm/friendlywrt_manifests -b master-v19.07.1 -m rk3328.xml --repo-url=https://github.com/friendlyarm/repo --no-clone-bundle
        repo sync -c --no-tags --no-clone-bundle -j8
        #cd friendlywrt/ && git fetch --unshallow

    - name: Update kernel-rockchip
      run: |
        #cd friendlywrt-rk3328
        #rm -rf kernel
        #git clone --single-branch -b nanopi-r2-v5.4.y https://github.com/friendlyarm/kernel-rockchip kernel
        #cd kernel
        #git remote add linux https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
        #git fetch linux
        #git rebase linux/linux-5.4.y

    - name: Merge Lean opwrt
      run: |
        cd friendlywrt-rk3328
        git clone https://github.com/coolsnowwolf/lede
        cd friendlywrt
        cp -r ../lede/package/lean package/
        sed -i 's/^src-git luci.*/src-git luci https:\/\/github.com\/coolsnowwolf\/luci/' feeds.conf.default
        sed -i 's/^src-git packages.*/src-git packages https:\/\/github.com\/coolsnowwolf\/packages/' feeds.conf.default
        sed -i '$a\src-git helloworld https://github.com/fw876/helloworld' ./feeds.conf.default
        ./scripts/feeds update -a   
        ./scripts/feeds install -a

    - name: Patch Kernel
      run: |
        cd friendlywrt-rk3328
        git clone https://github.com/openwrt/openwrt && cd openwrt/
        cp -a ./target/linux/generic/files/* ../kernel/
        ./scripts/patch-kernel.sh ../kernel target/linux/generic/backport-5.4
        ./scripts/patch-kernel.sh ../kernel target/linux/generic/pending-5.4
        ./scripts/patch-kernel.sh ../kernel target/linux/generic/hack-5.4
        ./scripts/patch-kernel.sh ../kernel target/linux/octeontx/patches-5.4

        cd ../
        wget https://github.com/torvalds/linux/raw/master/scripts/kconfig/merge_config.sh && chmod +x merge_config.sh
        grep -i '_NETFILTER_\|FLOW' ../r2s/.config.override > .config.override
        ./merge_config.sh -m .config.override kernel/arch/arm64/configs/nanopi-r2_linux_defconfig
        mv .config kernel/arch/arm64/configs/nanopi-r2_linux_defconfig
        sed -i -r 's/# (CONFIG_.*_ERRATUM_.*?) is.*/\1=y/g' kernel/arch/arm64/configs/nanopi-r2_linux_defconfig
   
    - name: Enable Fullcone NAT
      run: |
        cd friendlywrt-rk3328/kernel/
        wget -O net/netfilter/xt_FULLCONENAT.c https://raw.githubusercontent.com/Chion82/netfilter-full-cone-nat/master/xt_FULLCONENAT.c
        git apply ../../patches/000-kernel-add-full_cone_nat.patch
          
    - name: Enable 1.5G
      run: |
        cd friendlywrt-rk3328/kernel/
        wget https://github.com/armbian/build/raw/master/patch/kernel/rockchip64-dev/RK3328-enable-1512mhz-opp.patch
        git apply RK3328-enable-1512mhz-opp.patch

    - name: Enable cpu autocore
      run: |
        cd friendlywrt-rk3328/friendlywrt/
        git apply ../../patches/001-cpu-enable_autocore.patch

    - name: Install Extra Packages
      run: |
        cd friendlywrt-rk3328/friendlywrt/package
        #git clone https://github.com/fw876/helloworld
        #mv helloworld/luci-app-ssr-plus/ .   
                       
        git clone https://github.com/songchenwen/nanopi-r2s
        mv nanopi-r2s/luci-app-r2sflasher/ .
        rm -rf nanopi-r2s/
          
    - name: Update Target.mk
      run: |
        cd friendlywrt-rk3328/friendlywrt/include
        sed -i 's/dnsmasq /dnsmasq-full default-settings luci /' target.mk
       
    - name: Load config
      run: |
        rm -f friendlywrt-rk3328/friendlywrt/.config*
        cd friendlywrt-rk3328
        . ../r2s/remove_unused_config.sh
        cat configs/config_rk3328 | grep "TARGET" >> ../r2s/base_rk3328.seed  
        cat ../r2s/base_rk3328.seed > configs/config_rk3328
        cat ../$CONFIG_FILE >> configs/config_rk3328       

    - name: Mod
      run: |
        cd friendlywrt-rk3328/friendlywrt
        mv ../../r2s/check_wan4.sh package/base-files/files/usr/bin && sed -i '/exit/i\/bin/sh /usr/bin/check_wan4.sh &' package/base-files/files/etc/rc.local
        mv ../../r2s/update.sh package/base-files/files/root/update.sh && chmod +x package/base-files/files/root/update.sh
        . ../../$DIY_SH
        VersionDate=$(git show -s --date=short --format="date:%cd")
        echo "::set-env name=VersionDate::$VersionDate"
        echo "::set-env name=DATE::$(date "+%Y-%m-%d %H:%M:%S")"

    - name: Install UPX
      run: |
        ln -s /usr/bin/upx-ucl friendlywrt-rk3328/friendlywrt/staging_dir/host/bin/upx

    - name: Build FriendlyWrt
      run: |
        cd friendlywrt-rk3328
        ./build.sh nanopi_r2s.mk

    - name: Save config.seed
      run: |
        cd friendlywrt-rk3328/friendlywrt
        ./scripts/diffconfig.sh > ../out/config.seed
          
    - name: Organize files
      id: organize
      #if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        rm -rf ./artifact/
        mkdir -p ./artifact/
        gzip friendlywrt-rk3328/out/*.img
        mv friendlywrt-rk3328/out/*img* ./artifact/
        cp friendlywrt-rk3328/out/config.seed ./artifact/config-slim.seed
        cd ./artifact/
        zip R2S-slim-$(date +%Y-%m-%d).zip *.img.gz
        #rm *.img.gz
        echo "::set-env name=FIRMWARE::$PWD"
        echo "::set-output name=status::success"
        release_tag="NanoPi-R2S-${{ env.DATE }}-slim"
        echo "##[set-output name=release_tag;]$release_tag"
      
    - name: Upload artifact
      uses: actions/upload-artifact@master
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      with:
        name: OpenWrt_R2S_slim_firmware
        path: ${{ env.FIRMWARE }}

    - name: Create release
      id: create_release
      uses: ncipollo/release-action@v1.6.1
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        name: R2S最新编译时间:${{ env.DATE }}
        allowUpdates: true
        tag: R2S
        commit: master
        replacesArtifacts: true
        token: ${{ secrets.RELEASES_TOKEN }}
        body: |
          最新编译版本: ${{ steps.organize.outputs.release_tag }}
          源码最近更新时间: ${{ env.VersionDate }}
        artifacts: ${{ env.FIRMWARE }}/*.zip,${{ env.FIRMWARE }}/*.seed
