#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: Mod from P3TERX
#=================================================

name: Build R2S OpenWrt slim

on:
  release:
    types: published
  push:
    branches:
      - master
    paths:
      - '.config'
  schedule:
    - cron: 25 19 * * *
  watch:
    types: started

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  CONFIG_FILE: r2s.config
  DIY_SH: r2s_diy.sh
  SSH_ACTIONS: false
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: false
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d
        sudo apt-get update
        sudo apt-get -y --no-install-recommends install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf python3
        curl https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh  | sed '/#/d' | sed 's/\\//g' | sed 's/exit 0//g' | sed 's/sudo apt -y install//g' | sed 's/sudo apt-get -y install//g' | sed 's/:i386//g' | xargs sudo apt-get -y --no-install-recommends install
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk

    - name: Install Friendlyarm repo
      run: |
        git clone https://github.com/friendlyarm/repo
        sudo cp repo/repo /usr/bin/
        
    - name: Init Source
      run: |
        rm -rf friendlywrt-rk3328
        mkdir friendlywrt-rk3328
        cd friendlywrt-rk3328
        repo init -u https://github.com/friendlyarm/friendlywrt_manifests -b master-v19.07.1 -m rk3328.xml --repo-url=https://github.com/friendlyarm/repo --no-clone-bundle
        repo sync -c --no-clone-bundle
        #cd friendlywrt/ && git fetch --unshallow
         
    - name: Patch Kernel
      run: |
        . r2s/patch_kernel_5.4.sh
        sed -i -r 's/# (CONFIG_.*_ERRATUM_.*?) is.*/\1=y/g' kernel/arch/arm64/configs/nanopi-r2_linux_defconfig

    - name: Mods
      run: |
        cd friendlywrt-rk3328
        . ../r2s/remove_unused_config.sh
        cat configs/config_rk3328 | grep "TARGET" >> ../r2s/base_rk3328.seed  
        cat ../$CONFIG_FILE >> ../r2s/base_rk3328.seed
        cat ../r2s/base_rk3328.seed > configs/config_rk3328
        cd friendlywrt
        git config --local user.email "action@github.com" && git config --local user.name "GitHub Action"
        git remote add upstream https://github.com/Lienol/openwrt && git fetch upstream
        git checkout upstream/dev-lean-lede -b tmp
        git mv README.md README && git commit -m 'undo rename readme for rebasing'
        git checkout origin/master-v19.07.1
        git rebase adc1a9a3676b8d7be1b48b5aed185a94d8e42728^ --onto tmp -X theirs
        git revert --no-edit 8faac30089ce616940b3e96c4f4d900aeb6b9fcb
        sed -i '/ipv6/,+3d' package/base-files/files/root/setup.sh
        git checkout upstream/dev-lean-lede -- feeds.conf.default
        git apply ../../r2s/enable_autocore.diff
        mv ../../r2s/check_wan4.sh package/base-files/files/usr/bin && sed -i '/exit/i\/bin/sh /usr/bin/check_wan4.sh &' package/base-files/files/etc/rc.local
        mv ../../r2s/autoupdate-slim.sh package/base-files/files/root/au.sh && chmod +x package/base-files/files/root/au.sh
        . ../../$DIY_SH
        #useVersionInfo=$(git show -s --date=short --format="Author: %an<br/>date: %cd<br/>commit: %s<br/>commit hash: %H")
        useVersionDate=$(git show -s --date=short --format="date:%cd")
        echo "::set-env name=useVersionInfo::$useVersionInfo"
        echo "::set-env name=DATE::$(date "+%Y-%m-%d %H:%M:%S")"
            
    - name: SSH connection to Actions
      uses: P3TERX/debugger-action@master
      if: env.SSH_ACTIONS == 'true'

    - name: Build FriendlyWrt
      run: |
        cd friendlywrt-rk3328
        sed -i 's/set -eu/set -u/' scripts/mk-friendlywrt.sh
        ./build.sh nanopi_r2s.mk

    - name: Organize files
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        rm -rf ./artifact/
        mkdir -p ./artifact/
        mv friendlywrt-rk3328/out/*img* ./artifact/
        cp friendlywrt-rk3328/friendlywrt/.config ./artifact/
        #cp friendlywrt-rk3328/friendlywrt/.config ./friendlywrt-rk3328/out/
        #cd friendlywrt-rk3328/out
        cd ./artifact/
        gzip *.img
        echo "::set-env name=FIRMWARE::$PWD"
        echo "::set-output name=status::success"
        Release_tag="NanoPi-R2S-Lean-${{ env.DATE }}-slim"
        echo "##[set-output name=Release_tag;]$Release_tag"
        
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d')"
      
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt_R2S_slim_firmware
        path: ${{ env.FIRMWARE }}
      
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      if: steps.organize.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        repo_token: ${{ secrets.RELEASES_TOKEN }}
        file: ${{ env.FIRMWARE }}/*
        tag: ${{steps.date.outputs.date}}
        overwrite: true
        file_glob: true
      
#   - name: Create Release
#      id: create_release
#      uses: actions/create-release@v1
#      env:
#        GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}
#      with:
#        tag_name: ${{ steps.organize.outputs.Release_tag }}
#        release_name: R2S 精简版${{ steps.organize.outputs.Release_tag }}
#        body: |
#          Openwrt R2S 精简版
#          源码信息:
#          ${{ env.useVersionInfo }}
#        draft: false
#        prerelease: false
#
#    - name: Upload Release Asset
#      uses: svenstaro/upload-release-action@v1-release
#      with:
#        repo_token: ${{ secrets.RELEASES_TOKEN }}
#        file: ${{ env.FIRMWARE }}/*img.gz
#        #tag_name: R2S精简版
#        tag: ${{ steps.organize.outputs.Release_tag }}
#        overwrite: true
#        file_glob: true

#    - name: Upload Release Asset
#      id: upload-release-asset
#      uses: actions/upload-release-asset@v1
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
#      with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          asset_path: ${{ env.FIRMWARE }}/*.img.gz
#          asset_name: ${{ steps.organize.outputs.Release_tag }}-arm64_sd.img.gz
#          asset_content_type: application/gzip
