name: test create release
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/r2s_lean_slim.yml'
  schedule:
    - cron: '10 08 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
        token: ${{ secrets.RELEASES_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
